# Generated by Django 2.2.6 on 2019-10-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.CharField(default='w', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
